info:
    component: Config Server

server:
    port: 8888

spring:
    application:
        name: configserver
    autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    jmx:
        default_domain: cloud.config.server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Binvy/config-repo
                    clone-on-start: true

endpoints:
    restart:
        enabled: true

logging:
    level:
        root: info
        org.springframework.boot.env.PropertySourcesLoader: TRACE
        org.springframework.web: DEBUG